DROP TALBE SAILORS;

CREATE TABLE SAILORS
(
	sid INTEGER PRIMARY KEY,
	sname VARCHAR,
	rating INTEGER,
	age REAL
);

INSERT INTO SAILORS
	VALUES (22, 'Dustin', 7, 45.0);
INSERT INTO SAILORS
	VALUES (29, 'Brutus', 1, 33.0);
INSERT INTO SAILORS
	VALUES (31, 'Lubber', 8, 55.5);
INSERT INTO SAILORS
	VALUES (32, 'Andy', 8, 25.5;
INSERT INTO SAILORS
	VALUES (58, 'Rusty', 10, 35.0);
INSERT INTO SAILORS
	VALUES (64, 'Horatio', 7, 35.0);
INSERT INTO SAILORS
	VALUES (71, 'Zorba', 10, 16.0);
INSERT INTO SAILORS
	VALUES (74, 'Horatio', 9, 35.0);
INSERT INTO SAILORS
	VALUES (85, 'Art', 3, 25.5);
INSERT INTO SAILORS
	VALUES (95, 'Bob', 3, 63.5);